config/routes.rb
Rails.application.routes.draw do
  get 'items/index'

  resources :items

end

app/models/item.rb
class Item < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def new
  end

  def create
    @item = Item.new(item_params[:item])

    @item.save
    redirect_to @item
  end

  def show
    @item = Item.find(params[:id])
  end


private
  def item_params
    params.require(:item).permit(:name, :description, :estimate)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/index.html.erb
<h1>Items#index</h1>
<p>Find me in app/views/items/index.html.erb</p>

app/views/items/new.html.erb
<h1>New item</h1>

<%= form_for :item, url: items_path do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.label :estimate %><br>
    <%= f.text_field :estimate %>
  </p>

  <!-- TODO: Need to fix work estimate-->

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/items/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @item.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @item.description %>
</p>

<p>
  <strong>Cost Estimate (minutes):</strong>
  <%= @item.estimate %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Werk</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>